name: ayurayush_new
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  video_player: ^2.4.7
  razorpay_flutter: ^1.3.4
  google_sign_in: ^6.0.0
  carousel_slider: ^5.0.0
  http: ^1.3.0
  shared_preferences: ^2.0.0
  intl: ^0.18.0
  url_launcher: ^6.1.0
  path_provider: ^2.0.0
  permission_handler: ^10.0.0
  flutter_local_notifications: ^15.0.0
  image_picker: ^0.8.0
  file_picker: ^5.0.0
  pdf: ^3.8.0
  printing: ^5.9.0
  flutter_pdfview: ^1.3.0
  table_calendar: ^3.0.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/Pilopouse.jpg
    - assets/images/Prostostop.jpg
    - assets/images/saffron_care.jpg
    - assets/images/stomacalm.jpg
    - assets/images/vaji_cap.jpg
    - assets/videos/output.mp4
    - assets/images/logo-ayurayush.jpg
    - assets/videos/AAV_web.mp4
    - assets/videos/
    - assets/images/